name: Build MySQL 8 in Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker environment
        run: |
          # Pull latest Debian 12 (Bookworm) Docker image
          docker pull debian:bookworm

      - name: Build MySQL 8 in Debian 12 Docker container
        run: |
          docker run --rm -v $GITHUB_WORKSPACE:/workspace -w /workspace debian:bookworm bash -c "
            # Update and install essential packages
            apt update && apt install -y \
              build-essential \
              cmake \
              libssl-dev \
              libncurses5-dev \
              libaio-dev \
              bison \
              zlib1g-dev \
              wget \
              checkinstall \
              libcurl4-openssl-dev \
              libgoogle-perftools-dev \
              libjemalloc-dev \
              libedit-dev \
              libxml2-dev \
              libreadline-dev \
              libsasl2-dev \
              libbz2-dev \
              liblzma-dev \
              libjemalloc-dev \
              gcc \
              g++ \
              make \
              pkg-config \
              git \
              libpcre3-dev \
              libevent-dev \
              wget \
              tar \
              curl

            # Download and install Boost 1.77.0 manually (if needed)
            wget https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.tar.bz2
            tar -xjvf boost_1_77_0.tar.bz2
            cd boost_1_77_0
            ./bootstrap.sh
            ./b2 install

            # Download MySQL 8 source
            wget https://downloads.mysql.com/archives/get/p/23/file/mysql-8.0.37.tar.gz

            # Extract the source code
            tar -xvzf mysql-8.0.37.tar.gz

            # Move to MySQL source directory
            cd mysql-8.0.37

            # Create build directory and configure the build process
            mkdir build && cd build
            cmake .. -DWITH_SSL=system -DWITH_ZLIB=system -DWITH_BOOST=/workspace/boost_1_77_0

            # Compile MySQL
            make -j\$(nproc)

            # Use checkinstall to create a .deb package without installing it
            checkinstall -y --install=no --pkgname=mysql8 --pkgversion=8.0.37
          "

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mysql8-deb
          path: mysql-8.0.37/build/*.deb
